# 베이스 이미지
FROM python:3.10.12-slim

# 작업 디렉토리 설정
WORKDIR /code/app

# requirements.txt 복사 및 설치
COPY environments/requirements.txt .
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# 프로젝트 전체 복사 (컨텍스트 기준)
COPY . .

# Render에서 사용하는 포트 환경 변수로 uvicorn 실행
CMD ["sh", "-c", "uvicorn BE_p.main:app --host 0.0.0.0 --port $PORT"]
