# 베이스 이미지
FROM python:3.10.12-slim

# 작업 디렉토리 설정
WORKDIR /code/app

# requirements 복사 및 설치
COPY requirements.txt ./requirements.txt
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# 전체 소스 코드 복사
COPY . .

# Render에서 사용하는 포트 환경 변수로 uvicorn 실행
CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port $PORT"]
